# Generated by Django 3.0.7 on 2020-06-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asmr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='動画url')),
                ('info', models.CharField(blank=True, max_length=255, verbose_name='動画情報')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('asmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression', to='ababa.Asmr', verbose_name='ASMR')),
            ],
        ),
    ]
